package com.github.msu.sdk.request.enumerated;

public enum MessageContentType {
	INVITATION,
	FORGOT_PASSWORD,
	INVITE_MERCHANT_USER,
	EMAIL_HEADER,
	EMAIL_FOOTER,
	PAYBYLINK_EMAIL,
	PAYBYLINK_SMS,
	PAYBYLINK_REMIND_EMAIL,
	PAYBYLINK_REMIND_SMS,
	RECURRING_ADDCARD_EMAIL,
	RECURRING_EDITCARD_EMAIL,
	RECURRING_ADDCARD_SMS,
	RECURRING_EDITCARD_SMS,
	TAC,
	SECURITY,
	FAQ,
	PRIVACY,
	VOID_REFUND_POLICY,
	CONTACT,
	CARD_SAVING_TAC;
}
