package com.payten.sdk.msu.request.enumerated;


public enum PaymentProcessor {
    PROCESSOR_NESTPAY,
    PROCESSOR_GARANTI,
    PROCESSOR_YKB,
    PROCESSOR_VAKIF,
    PROCESSOR_ODEA,
    PROCESSOR_INTESA,
    PROCESSOR_KUVEYT,
    PROCESSOR_WIRECARD,
    PROCESSOR_HSBC,
    PROCESSOR_PARATIKA,
    PROCESSOR_IYZICO,
    PROCESSOR_QNB_FINANS,
    PROCESSOR_PAYU,
    PROCESSOR_DENIZ,
    PROCESSOR_BKMEXPRESS,
    PROCESSOR_BKMEXPRESSV2,
    PROCESSOR_COMPAY,
    PROCESSOR_EMULATOR,
    PROCESSOR_GARANTIPAY,
    PROCESSOR_PAYU3D;
}
