//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.16 at 04:16:18 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.asseco-see.com.tr/schema-action-rules", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.payten.sdk.msu.generator;
